[package]
name = "sui-validator-failover"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[[bin]]
name = "sui-validator-agent"
path = "src/main.rs"

[[bin]]
name = "sui-validator-control"
path = "src/bin/control.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
bcs.workspace = true
clap.workspace = true
fastcrypto.workspace = true
hex.workspace = true
prost.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
telemetry-subscribers.workspace = true
thiserror.workspace = true
sui-validator-signer.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tonic-prost.workspace = true
tracing.workspace = true

[build-dependencies]
tonic-build.workspace = true

[dev-dependencies]
consensus-config.workspace = true
fastcrypto-tbls.workspace = true
rcgen = "0.13.1"
sui-types.workspace = true
tempfile = "3.3.0"
tokio-stream.workspace = true
